@APIURL = http://localhost:3001
//GET THE LIST OF APPLICATION
GET {{APIURL}}/professor/1/applications
###  
//UPDATE THE APPLICATION STATUS (PROFESSOR TASK)
POST {{APIURL}}/professor/2/applications/1
content-type: application/json

{
    "accepted" : 1
}
###
POST {{APIURL}}/testing/vc/set
Content-Type: application/json

{
    "value": "2024-12-24T23:59"
}
###
POST {{APIURL}}/testing/vc/restore
Content-Type: application/json

{
    "value": 1
}

### 
GET  {{APIURL}}/testing/vc/get
Content-Type: application/json
### 
GET  {{APIURL}}/professor/thesis
Content-Type: application/json
